server:
  port: 9090
  servlet:
    context-path: /bank/v1
  session:
    timeout: 300
  profiles:
    active: "dev"
config:
    data:
      url: "jdbc:ucanaccess://C:/Users/lalsaadi/work/code/bank-java-service/account-ms/src/main/resources/accountsdb.accdb"
      driver-class-name: "net.ucanaccess.jdbc.UcanaccessDriver"

